name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Good job!"
      - run: npm ci
      - npm: test
        uses: actions/checkout@v3